server:
  port: ${PORT:8095}

spring:
  application:
    name: game-api

  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

  datasource:
    url: jdbc:postgresql://localhost:5432/game-api
    username: ${POSTGRES_ROOT_USER:postgres}
    password: ${POSTGRES_ROOT_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  # true em dev para ver as queries geradas
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

app:
  auth:
    token-secret: ${JWT_TOKEN_SECRET}
    token-expiration-msec: 900000
    refresh-token-expiration-msec: 604800000

logging:
  level:
    root: INFO
    br.com.study.gameapi: DEBUG  # logs detalhados só do nosso código